### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by smickles** [Meigs2/REvernus#5]
I've downloaded dotnet3.0, vs2019, loaded REvernus and hit F5, result: 

```System.IO.DirectoryNotFoundException
  HResult=0x80070003
  Message=Could not find a part of the path 'C:\Users\Michael\AppData\Local\REvernus\Data\db\user.db'.
  Source=System.Private.CoreLib
  StackTrace:
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at System.Data.SQLite.SQLiteConnection.CreateFile(String databaseFileName)
   at REvernus.Utilities.StaticData.DatabaseManager.CreateUserDataTable() in C:\msys64\home\Michael\REvernus\REvernus\Utilities\StaticData\DatabaseManager.cs:line 77
   at REvernus.Utilities.StaticData.DatabaseManager.<Initialize>d__3.MoveNext() in C:\msys64\home\Michael\REvernus\REvernus\Utilities\StaticData\DatabaseManager.cs:line 56
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at REvernus.Utilities.StartupAndExit.<PerformStartupActions>d__1.MoveNext() in C:\msys64\home\Michael\REvernus\REvernus\Utilities\StartupAndExit.cs:line 17
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at REvernus.App.<Application_Startup>d__5.MoveNext() in C:\msys64\home\Michael\REvernus\REvernus\App.xaml.cs:line 22
```

appdata\local\REvernus doesn't even exit yet :P

**Comment by Meigs2** [comment]
Ah, thanks for pointing this out! I'll quickly push an update.

**Comment by Meigs2** [comment]
If the problem persists, let me know :)
